### PR TITLE
Css three column layout | Heesoo Kim

### PR DESCRIPTION
**Pull request by heesoo-kim97**
Screen Shot 2021-06-25 at 5 41 46 PM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Heesoo!! The edges of your images are cut off, please address this. Rather than rounding the border of the image, you should put the `img` in a `div`, and make that `div` the white circle.

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Heesoo! When visual changes are requested, make sure you attach a new screenshot of your output. Please message me on Slack once you have uploaded a new screenshot, I won't get a notification for the new image

**Comment by heesoo-kim97** [comment]
Screen Shot 2021-06-28 at 9 34 11 PM

**Review by codingcodymiller — APPROVED** [review]
Fantastic work on this!! 🎉 🎉 🎉 🎉

**Pull request merged**
